### PR TITLE
fix default values for attributes of CelestialFrame

### PR DESCRIPTION
**Pull request by nden**
This is a second attempt for a work around issue #21

### CODE REVIEW

**Comment by mdboom** [comment]
Thanks!  That helps a lot.

I'm still seeing problems with Galactocentric and ITRS, though:

```
        cf.CelestialFrame(
            reference_frame=coord.Galactocentric(
                galcen_distance=5.0*u.m,
                galcen_ra=45*u.deg,
                galcen_dec=1*u.rad,
                z_sun=3*u.pc,
                roll=3*u.deg)
            )
```

gives:

```
self = <[AttributeError("'CelestialFrame' object has no attribute '_name'") raised in repr()] SafeRepr object at 0x7f3a35675fc8>
axes_order = (0, 1)
reference_frame = <Galactocentric Frame (galcen_distance=5.0 m, galcen_ra=45.0 deg, galcen_dec=1.0 rad, z_sun=3.0 pc, roll=3.0 deg)>
unit = (Unit("deg"), Unit("deg")), axes_names = ['x', 'y', 'z'], name = None, wcsobj = None

    def __init__(self, axes_order=(0, 1), reference_frame=None,
                 unit=(u.degree, u.degree), axes_names=None,
                 name=None, wcsobj=None):
        naxes = 2
        if reference_frame is not None:
            if reference_frame.name.upper() in STANDARD_REFERENCE_FRAMES:
                axes_names = list(reference_frame.representation_component_names.values())
                if 'distance' in axes_names:
                    axes_names.remove('distance')
    
                naxes = len(axes_names)
        super(CelestialFrame, self).__init__(naxes=naxes, axes_type=["SPATIAL", "SPATIAL"],
                                             axes_order=axes_order,
                                             reference_frame=reference_frame,
                                             unit=unit,
                                             axes_names=axes_names,
>                                            name=name, wcsobj=wcsobj)

/home/mdboom/python/lib/python2.7/site-packages/gwcs-0.1.dev75-py2.7.egg/gwcs/coordinate_frames.py:290: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError("'CelestialFrame' object has no attribute '_name'") raised in repr()] SafeRepr object at 0x7f3a356157a0>
naxes = 3, axes_type = ['SPATIAL', 'SPATIAL'], axes_order = (0, 1)
reference_frame = <Galactocentric Frame (galcen_distance=5.0 m, galcen_ra=45.0 deg, galcen_dec=1.0 rad, z_sun=3.0 pc, roll=3.0 deg)>
reference_position = None, unit = (Unit("deg"), Unit("deg")), axes_names = ['x', 'y', 'z']
name = None, wcsobj = None

    def __init__(self, naxes, axes_type, axes_order, reference_frame=None,
                 reference_position=None, unit=None, axes_names=None,
                 name=None, wcsobj=None):
        self._naxes = naxes
        self._axes_order = axes_order
        if isinstance(axes_type, six.string_types):
            self._axes_type = (axes_type,)
        else:
            self._axes_type = axes_type
        self._reference_frame = reference_frame
        if unit is not None:
            if astutil.isiterable(unit):
                if len(unit) != naxes:
>                   raise ValueError("Number of units does not match number of axes.")
E                   ValueError: Number of units does not match number of axes.

/home/mdboom/python/lib/python2.7/site-packages/gwcs-0.1.dev75-py2.7.egg/gwcs/coordinate_frames.py:68: ValueError
```

**Comment by mdboom** [comment]
To reproduce, you can run the tests in https://github.com/spacetelescope/pyasdf/pull/165 after uncommenting the lines in `test_wcs.py`.

**Comment by nden** [comment]
@mdboom  I can't reproduce this . All tests are passing for me (except one in generic_io ), including the tests for Galactocentric and ITRS.

**Comment by mdboom** [comment]
Ah -- I think I needed to update astropy as well.  Doing that, everything passes.  Thanks.

**Pull request merged**
