### PR TITLE
Add support for relative time in APE 14

### PR DESCRIPTION
**Pull request by Cadair**
This is a fix for #252 

We need to provide a way to instantiate a `Time` object with a time delta for APE 14 to work. This is the cleanest way I can think of.

### CODE REVIEW

**Comment by Cadair** [comment]
@nden this is now based on astropy/astropy#9376 (so requires 4.0 dev) but I think this is now the canonical way to solve this.

**Comment by nden** [comment]
@Cadair I merged this one too soon. It broke the tests on master. Could you look at the errors

https://travis-ci.org/spacetelescope/gwcs/builds/620639291

Can you submit a fix? Or should I revert?

**Comment by Cadair** [comment]
oh yeah. This needs 4.0.

I am not sure if there is a clean way to fail on <4.0 though.

**Comment by nden** [comment]
Ah, that's fine then. I'll keep checking the dev jobs only. Thanks.

**Comment by jdavies-st** [comment]
If you want to make this test skip for `astropy<4.0`, you can do something like
```
@fixture_all_wcses
def test_high_level_wrapper(wcsobj):
    pytest.importorskip("astropy", minversion="4.0")
    hlvl = HighLevelWCSWrapper(wcsobj)
```
which will make it skip on all parametrizations of this test.

If you want to make it only skip on the parametrized test of interest:
```
@fixture_all_wcses
def test_high_level_wrapper(wcsobj, request):
    if request.node.callspec.params['wcsobj'] == 'gwcs_4d_identity_units':
        pytest.importorskip("astropy", minversion="4.0")
    hlvl = HighLevelWCSWrapper(wcsobj)
```

**Comment by Cadair** [comment]
see #262

**Pull request merged**
