### PR TITLE
Fix APE 14 API with 1D CoordinateFrame object

### PR DESCRIPTION
**Pull request by Cadair**
I think this solves it properly, I haven't had time to test if it actually fixes my ndcube issue.

### CODE REVIEW

**Comment by nden** [comment]
@Cadair So does this fix your ndcube issue?

**Comment by Cadair** [comment]
It looks like there was something else also in the way, but this fixed at least one of the issues.

**Comment by nden** [comment]
There's an issue with Stokes frame which I can fix after this is merged.

**Review by nden — APPROVED** [review]

**Comment by nden** [comment]
I'm going to merge this. File an issue or submit another PR if there's a different problem.

Closes #406

**Pull request merged**
