### PR TITLE
Refactor `axis_physical_types`

### PR DESCRIPTION
**Pull request by Cadair**
This is the second part of #457

The main work here is refactoring the logic of deciding the default coordinate frames from the base class into subclasses. Also add a `PixelFrame` which supports multiple dimensions. I haven't done anything with `Frame2D` here, but imo this is a complete replacement for it?

### CODE REVIEW

**Comment by nden** [comment]
These changes look good to me overall. It's unclear what the return type should be. In the FITS implementation it's defined as `iterable` and the examples return a list. GWCS uses tuples. How important is to be consistent т тхат лежел?

The new `PixelFrame` does not add much, however if it's convenient, I'm fine with adding it. I should note that there are no tests with this PR. And the new frame will need a `Converter`. 
JWST regression tests pass: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/750/

**Comment by Cadair** [comment]
I would say tuple rather than a list is perfectly fine, iterable is iterable. :shrug:

**Review by nden — APPROVED** [review]

**Comment by nden** [comment]
Failure is unrelated

**Comment by nden** [comment]
@Cadair I'm trying to sort out the jwst regression tests and once done will merge this.

**Pull request merged**
