### PR TITLE
fix issue #21

### PR DESCRIPTION
**Pull request by nden**
This is a work around #21: `distance` is removed from the list of component names. Also `naxes`  is set as `len(axes_names` in the reference_frame or 2.

### CODE REVIEW

**Comment by mdboom** [comment]
Thanks!  That was fast.

Now there seems to be a related problem to that in that `len(unit)` != `naxes` and `len(axes_type)` != `naxes`.

I don't know if there's a way to get "default units" from the coordinate frame object, but in some cases here I guess it's (angle, angle, distance) rather than just (angle, angle).

**Comment by nden** [comment]
Hm, is this specific to galactocentric?

**Comment by mdboom** [comment]
It seems to be any of the coordinate frames with 3 axes -- Galactocentric, FK4NoETerms, Galactic, ITRS and PrecessedGeocentric.

**Comment by eteq** [comment]
Oops, I didn't see this until after leaving a comment in #21... but I think it's actually more right for `naxes` to *always* be ``3``, not ``2``: that's fundamental to the design of ``coordinates`` and the representation objects.

**Pull request merged**
