### PR TITLE
move configuration into `pyproject.toml`

### PR DESCRIPTION
**Pull request by zacharyburnett**
in line with PEP621, with the new `setuptools`; this also future-proofs against uses of a PEP517 build like in the new Tox update

### CODE REVIEW

**Review by pllim — COMMENTED** [review]
I don't really work on this package, so I'll defer to the maintainers to review this.

**Comment by WilliamJamieson** [comment]
Could you rebase this and push. I'm not sure why the docs are failing

**Comment by WilliamJamieson** [comment]
The docs are still failing...

**Comment by WilliamJamieson** [comment]
I think rebasing will fix the failing tests.

**Review by WilliamJamieson — APPROVED** [review]

**Review by mcara — APPROVED** [review]

**Pull request merged**
