### PR TITLE
Infrastructure update

### PR DESCRIPTION
**Pull request by bsipocz**
Including:

  -  fix miniconda prefix (that causes travis failures at the moment)
  -  update helpers to 1.0.5
  -  opt in to container based travis
  -  customize test header

### CODE REVIEW

**Comment by nden** [comment]
@bsipocz Thanks for updating! Should we wait for astropy/package-template#139 to be resolved and used instead of this ?

**Comment by bsipocz** [comment]
Yes, I think it would be better as it will be more future proof of any ci changes.
I can update this PR when we are ready.

**Comment by bsipocz** [comment]
Also I have to fix the travis failure, too.

**Comment by nden** [comment]
@bsipocz Should we merge this as is (after fixing the error) and then update `package-template` when  astropy/package-template#139 is merged?

**Comment by bsipocz** [comment]
@nden - astropy/package-template#140 supersedes astropy/package-template#139 to use the package ``ci-helpers``. If you plan to use it, too,  I can update this PR while fixing the errors.

**Comment by nden** [comment]
Yes, please update it to use `ci-helpers`. Thanks!

**Comment by bsipocz** [comment]
The fail is fixed by https://github.com/spacetelescope/pyasdf/pull/180

**Comment by bsipocz** [comment]
@nden - It seems that spacetelescope/pyasdf#180 indeed works: https://travis-ci.org/spacetelescope/gwcs/builds/94295848

Once it's merged this can be merged, too.
(since that travis test I've removed testng against stable astropy (as 1.1 is required for pyasdf), and also removed the temporary workaround commit https://github.com/spacetelescope/gwcs/commit/0628717f6087a7f9cae7e658a017975ca05013e6)

**Pull request merged**
