### PR TITLE
TST: fix usage of doctestplus FLOAT_CMP

### PR DESCRIPTION
**Pull request by bsipocz**
This failing doctest was reported upstream (https://github.com/astropy/pytest-doctestplus/issues/135), but I think the source of the failing test was that the doctest comment was put on the wrong line.

### CODE REVIEW

**Review by mcara — COMMENTED** [review]
I tried testing this PR locally on my laptop and I am getting even more differences:
```python
Differences (unified diff with -expected +actual):
    @@ -1,10 +1,10 @@
    -Indices of diverging points: None
    -Indices of poorly converging points: [1]
    +Indices of diverging points: [1]
    +Indices of poorly converging points: None
     Best solution:
    -[[1.00000040e+00 1.99999841e+00]
    +[[1.00000039e+00 1.99999838e+00]
      [6.33507833e+17 3.40118820e+17]
    - [3.00000038e+00 4.99999841e+00]]
    + [3.00000038e+00 4.99999837e+00]]
     Achieved accuracy:
    -[[2.75878040e-05 1.16619263e-05]
    - [9.16724833e+06 1.63643914e+06]
    - [2.76552923e-05 1.14789013e-05]]
    +[[2.75878040e-05 1.16635321e-05]
    + [4.02831860e+06 2.66521911e+06]
    + [2.76506125e-05 1.14766428e-05]]
```

**Comment by mcara** [comment]
I am not convinced that `FLOAT_CMP` works on _printed_ values as opposite to values returned by the calling function. Also, print statements are in the `except` block. Shouldn't those have `# doctest: +FLOAT_CMP`?

Maybe @embray 🤞 could take a look at this.

**Comment by bsipocz** [comment]
> I am not convinced that FLOAT_CMP works on printed values as opposite to values returned by the calling function. Also, print statements are in the except block. Shouldn't those have # doctest: +FLOAT_CMP?


without diving into the details, but my expectation is that the actual arrays are generated by the line I added the comment on. All the rest around it is to pass it though. I may be wrong, and don't have time to dig up the details (that being said, I think this is the first time that I see try/except in a docstring, and this is certainly a case that I didn't see covered in upstream tests so my expectation and actual and desired behaviour may be way off from each other).

All that being said, maybe the right place for the comments are indeed on the actual print lines in the except, and then I just got lucky that it worked with my patch.

**Comment by nden** [comment]
It seems this is not a problem any more. I'll close it but if anyone feels otherwise feel free to reopen.

**Pull request closed without merging**
